library(shiny)
library(shinyjs)

ui <- fluidPage(
  tags$head(tags$style(
    HTML(
      "
        h3:first-of-type {
          font-weight: bold;
        }
        .indented-section {
          padding-left: 30px
        }
      "
    )
  )),
  titlePanel(div(
    span("Final Project:"), "Crime Data Analysis in Seattle"
  )),
  style = "background-color: #e8bebe;",
  tabsetPanel(
    id = "tabs",
    tabPanel(
      "Home",
      div(
        img(
          src = "seattle_crime.png",
          alt = "Crime",
          width = "150px",
          height = "200px",
          style = "position: absolute; top: 10px; left: 700px;"
        ),
      ),
      
      h3("INFO 201 Foundational Skills for Data Science"),
      
      h4("Name: Kenta Lipsey (klipsey@uw.edu)"),
      h4("Date: Spring 2024"),
      h3(
        "WARNING: This is a MASSIVE data set and may take long to load!",
        style = "font-weight: bold"
      ),
      div(div(
        h2("Introduction:"),
        div(
          class = "indented-section",
          p(
            "This application is a thorough examination of Seattle's crime reports, focusing on crime types, details, and locations. By compiling and analyzing this data, I aim to identify crime hotspots and prevalent crime categories, providing valuable insights into the city's underlying issues. Understanding the root causes behind criminal behavior enables us to adopt proactive measures to address societal problems effectively. Through this data-driven approach, we can work towards creating a safer and more resilient community for all residents."
          )
        )
      )),
      
      div(div(
        h2("What & Why:"),
        div(
          class = "indented-section",
          p(
            "Crime data analysis is instrumental in understanding, preventing, and responding to criminal activities, benefiting society in various ways. It identifies crime hotspots, enabling law enforcement to allocate resources efficiently and reduce response times, thus deterring criminal behavior. Additionally, it aids in developing evidence-based crime prevention strategies by identifying underlying factors contributing to criminal behavior. This includes socio-economic conditions, environmental factors, and social networks, leading to targeted interventions and safer communities. Moreover, crime data analysis evaluates the effectiveness of criminal justice policies and interventions, guiding resource allocation and policy reforms for more efficient and equitable systems. Crime Categories, crime data analysis serves as a powerful tool for enhancing public safety and well-being. For further exploration, resources such as articles from reputable law enforcement publications, research papers on spatial analysis techniques, and discussions on big data analytics' potential in crime prevention offer valuable insights into this field."
          )
        )
      )),
      
      div(div(
        h2("The Dataset:"),
        div(
          class = "indented-section",
          p(
            "https://www.seattle.gov/police/information-and-data/data/public-data-sets and https://data.seattle.gov/browse/select_dataset?tags=beats I found these data on the seattle.gov website and it holds a whopping 1,122,474 observables and crime beats. This data was collected by our government. These data sets are collected and generated by the police whenever an arrest happens. This data was collected in order to keep track of crime data over time in the city of seattle. This also helps law enforcement prioritize specific areas that are more common for crime. There are over 1 million rows and 17 columns. Ethical questions to consider is the idea of predictive policing. In the past, data like this was used in algorithms to predict crime before it happens. This would often cause police to interrogate individuals before any indication of crime simply because an algorithm said so. This is highly unethical since the algorithm is bias and will pick people based on features that do not nesscarily indicate their likelyhood of crime. The issues with this data is that it requires an additional dataset to be proper affected. This can include a data set that also maps out zip code areas or locational features so that the crime data can be visualized properly when imported into a data visualizer."
          )
        )
      )),
      
      div(div(
        h2("Implications:"),
        div(
          class = "indented-section",
          p(
            "If properly examined, this dataset can help people factor in crime when it comes to many decisions. This could be something simple like picking where to live or where to eat next but it can also be scaled to changes in policies within our government. For example, if crime levels are increasing in certain areas that haven't been maintained (roads, buildings, cleanliness) the government can put funds towards repairing the area. If crime increases in more wealthy locations and the highest crime is theft of some sort, policies to address class issues could be brought up to help those who feel as if they need to resort to crime in order to survive. Crime is an indication of bigger issues in our society and this data should be used to address them instead of bandaging the issue by only arresting those who commit crimes."
          )
        )
      )),
      
      div(div(
        h2("Limitations:"),
        div(
          class = "indented-section",
          p(
            "Crime data analysis has a few big problems that make it hard to get useful information. First, the data comes from lots of different places and formats, so it's a lot of work to combine and clean it up. Second, we have to be very careful about privacy because the data is sensitive. Another problem is bias. This can come from unfair practices in the past or mistakes in how data is collected. To fix this, we need to focus on being fair, clear, and responsible in our analysis. To really benefit from crime data analysis, we need to use strong methods that deal with these biases and make sure our results are accurate and fair. By solving these problems, we can come up with better ways to prevent crime and make our communities safer and fairer.."
          )
        )
      )),
    ),
    
    tabPanel("Crime by Location",
             sidebarLayout(
               sidebarPanel(
                 p(
                   "This chart displays the amount of offenses per location/district in Seattle."
                 ),
                 uiOutput("overall")
               ),
               mainPanel(plotlyOutput("location_chart"))
             )),
    
    tabPanel("Beat Map",
             sidebarLayout(
               sidebarPanel(
                 p(
                   "This chart shows how different areas of Seattle have been affected by crime from 2008 to 2018. Press the checkboxes to see different areas and locations"
                 ),
                 checkboxGroupInput(
                   "years",
                   "Select Time Periods:",
                   choices = list(
                     "2008-2015" = "2008_2015",
                     "2015-2017" = "2015_2017",
                     "2017-2018" = "2017_2018"
                   ),
                   selected = c("2008_2015", "2015_2017", "2017_2018")
                 ),
               ),
               mainPanel(plotOutput("beat_map"))
             )),
    
    tabPanel("Crime Categories",
             sidebarLayout(
               sidebarPanel(
                 p(
                   "This chart displays the crime rate data sorted by crime categories."
                 ),
                 uiOutput("overall")
               ),
               
               mainPanel(plotlyOutput("offense_year"))
             )),
    tabPanel(
      "Summary Information",
      p("A summary of of all data available."),
      verbatimTextOutput("summary")
    ),
    tabPanel(
      "Table",
      tableOutput("summary_table"),
      tableOutput("crime_summary_table")
    )
  )
)
